# Generated by Django 2.2 on 2019-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('command', models.CharField(max_length=300)),
                ('img', models.ImageField(blank=True, upload_to='imgs')),
            ],
        ),
    ]
