# Generated by Django 2.2 on 2019-04-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='title',
        ),
    ]
